language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: grztiZizePYyW/poK8rq/IP9UYgBr1Jvxj/LTJ2+yJvQg+ul75RgEf+um48VYYxB1QVaBIRfx0pGTQH/CzrK3ZazH2AJovzIqWpiYMOhFc1VwzgCii8k77fey4BMxUYcYcc8uYOwPrG5pWZ7q/dJgqsm9TQ745ePmRDDcezOVrx89gjkOeNyVyNAm6lwfDvhdYPf06ySrtqoQQ07vR1YQEqMS5YPZuqsX839fZhWt0gbpelPMqjyxo37lqVB9s+p/Fy2L4C55H8u/GyhR/BBERNZ5prHhkeZ2/zaCkLfD/oup9ZBitNXM81tVENE/67ovuuxqVonrsXPQQ+xjfeOYcZ4MW8fgv4KBFGaGrLmj2f9B88l7rl2YavO3NK5q6kWhTzlqtPi2VfBJ74KkAXvVh0UQ/GcsRaK4Kyxp3enN/zqi2RXfy8Fn9sXjcYvv4I/LYSBwcP9Th/QF8HvUOLSsPednWmeGOtn4Vj3N5ip9Z4LbhAjmYEqX5Mx6LKGOpm/FKyFGYAERGEcuQMYo3+wxiNXaOd1rUJUhp4ryRAq9sd3TTEmh+cxEjk+gmXqcF6w92S5hef5fF6svMnXgPKbeFf2rBXF+eKd4y6c5HgVj+TS7P4J8Kv05sOBw9L+0yc1rlUMQm6MhBYMSWmQ6dG2oF43ObkYeJn8CPdwhGm8Ku0=
  file:
    - 'is-hexadecimal.js'
    - 'is-hexadecimal.min.js'
  on:
    tags: true
